### ISSUE TITLE
Cannot find module './stringFormat'

### ISSUE THREAD

**Issue by axllent** [gorriecoe/atom-silverstripe#10]
With atom-silverstripe@3.2.1 I'm getting the following error:
```
Error: Cannot find module './stringFormat'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///opt/atom/resources/app/static/index.js:40:43)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/ralph/.atom/packages/atom-silverstripe/lib/allAutocompletes.js:4:24)
    at Object.<anonymous> (/home/ralph/.atom/packages/atom-silverstripe/lib/allAutocompletes.js:119:32)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/ralph/Nextcloud/Documents/Configs/atom/packages/atom-silverstripe/lib/main.js:7:25)
    at Object.<anonymous> (/home/ralph/.atom/packages/atom-silverstripe/lib/main.js:62:2)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/opt/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app/src/package.js:887:35)
    at /opt/atom/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/opt/atom/resources/app/src/package.js:144:18)
    at PackageManager.module.exports.PackageManager.loadAvailablePackage (/opt/atom/resources/app/src/package-manager.js:565:22)
    at /opt/atom/resources/app/src/package-manager.js:479:25
```

Atom v1.19.3

**Comment by gorriecoe** [comment]
Hey @axllent,  Could you check if there is a red bug icon on the bottom right of atom.   Sometimes atom doesn't build a package properly after updating.  If you click the bug it should prompt you to rebuild.

**Comment by gorriecoe** [comment]
If that fails try re-install the package.

**Comment by axllent** [comment]
There is no bug icon at the bottom right, and I did uninstall & reinstall the package prior to the bug report.

I realise that Atom isn't at the latest version  (1.19.3 installed; 1.19.5 latest), however I doubt that the minor Atom update version would affect this.

Is there supposed to be a stringFormat module included with atom-silverstripe as I can confirm that there isn't here nor a reference to it (only a reference to `isStringFormat` in the included `node_modules/eslint/lib/rules/no-restricted-syntax.js`), so I'm a bit confused ;-)

I'll gladly try any other suggestions you may have?

**Comment by gorriecoe** [comment]
Hey @axllent,  I have updated the module.  Can you confirm that 3.2.2 fixes the issue?

**Comment by axllent** [comment]
@gorriecoe You're a star, that fixes the issue, thank you! It seems case **does** matter on non-Windows systems ;-)

**Comment by axllent** [comment]
Ans as a last note I realised that my previous comment about not being able to find the file was incorrect - I was looking in the wrong module lol. Either way though, your 3.2.2 fix does fix it. Thanks again.
